version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bd_soyucab_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Soy_UCAB
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./Tercera_Entrega_Proyecto_10.sql:/docker-entrypoint-initdb.d/Tercera_Entrega_Proyecto_10.sql

  jsreports:
    image: jsreport/jsreport:3.11.3
    container_name: bd_soyucab_reports
    ports:
      - "5489:5488"
    environment:
      extensions_postgresStore_host: db
      extensions_postgresStore_port: 5432
      extensions_postgresStore_user: postgres
      extensions_postgresStore_password: password
      extensions_postgresStore_database: Soy_UCAB
      # We just mount a local folder to persist templates
    volumes:
      - ./jsreport_data:/app/data
    depends_on:
      - db
